# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import gram.models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default=gram.models.generate_id, max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
