# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='posts',
        ),
    ]
