# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_auto_20171128_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
